version: '3.8'

services:
  # Milvus 벡터 데이터베이스 - standalone 설정
  milvus:
    image: milvusdb/milvus:v2.3.2
    container_name: milvus-standalone
    ports:
      - "19530:19530"
      - "9091:9091"
    command: ["milvus", "run", "standalone"]
    environment:
      - ETCD_USE_EMBED=true
      - ETCD_DATA_DIR=/var/lib/milvus/etcd
      - COMMON_STORAGETYPE=local
      - MINIO_ADDRESS=localhost
      - MINIO_ACCESS_KEY=minioadmin
      - MINIO_SECRET_KEY=minioadmin
    volumes:
      - milvus_data:/var/lib/milvus
    networks:
      - vector_net
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9091/healthz"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 90s
    restart: always

  # Milvus 대시보드 (Attu)
  attu:
    image: zilliz/attu:v2.3.2
    container_name: attu
    ports:
      - "8000:3000"
    environment:
      - MILVUS_URL=milvus:19530
    networks:
      - vector_net
    depends_on:
      - milvus
    restart: always

volumes:
  milvus_data:
    driver: local

networks:
  vector_net:
    driver: bridge