[formatters]
keys=generic, gunicorn_access

[formatter_generic]
format=%(asctime)s %(process)d (%(levelname)s) %(name)s >> %(message)s
datefmt=%Y-%m-%d %H:%M:%S
class=logging.Formatter

[formatter_gunicorn_access]
format=[%(asctime)s %(msecs)s] %(message)s
datefmt=%Y-%m-%d %H:%M:%S
class=logging.Formatter


[loggers]
keys=root, gunicorn.error, gunicorn.access

[logger_root]
level=INFO
handlers=console

[logger_gunicorn.error]
level=INFO
handlers=error_file
propagate=1
qualname=gunicorn.error

[logger_gunicorn.access]
level=INFO
handlers=access_file
propagate=0
qualname=gunicorn.access


[handlers]
keys=console, error_file, access_file

[handler_console]
class=StreamHandler
formatter=generic
args=(sys.stdout, )

[handler_error_file]
class=logging.FileHandler
formatter=generic
args=('/var/log/jypark/quiz-api/gunicorn.error.log', 'a')
# NOTE: # mode='a'는 append 모드로, 파일이 없으면 자동 생성

[handler_access_file]
class=logging.FileHandler
formatter=gunicorn_access
args=('/var/log/jypark/quiz-api/gunicorn.access.log', 'a')